export const ciudadesAcotado = [
  { value: "CORDOBA", label: "CORDOBA" },
  { value: "VILLA ALLENDE", label: "VILLA ALLENDE" },
  { value: "VILLA CARLOS PAZ", label: "VILLA CARLOS PAZ" },
];

export const ciudades = [
  { value: "ACHIRAS", label: "ACHIRAS" },
  { value: "ADELIA MARIA", label: "ADELIA MARIA" },
  { value: "AGUA DE ORO", label: "AGUA DE ORO" },
  { value: "ALCIRA", label: "ALCIRA" },
  { value: "ALDEA SANTA MARIA", label: "ALDEA SANTA MARIA" },
  { value: "ALEJANDRO ROCA", label: "ALEJANDRO ROCA" },
  { value: "ALEJO LEDESMA", label: "ALEJO LEDESMA" },
  { value: "ALICIA", label: "ALICIA" },
  { value: "ALMAFUERTE", label: "ALMAFUERTE" },
  { value: "ALPA CORRAL", label: "ALPA CORRAL" },
  { value: "ALTA GRACIA", label: "ALTA GRACIA" },
  { value: "ALTO ALEGRE", label: "ALTO ALEGRE" },
  { value: "ALTO DE LOS QUEBRACHOS", label: "ALTO DE LOS QUEBRACHOS" },
  { value: "ALTOS DE CHIPION", label: "ALTOS DE CHIPION" },
  { value: "AMBOY", label: "AMBOY" },
  { value: "AMBUL", label: "AMBUL" },
  { value: "ANA ZUMARAN", label: "ANA ZUMARAN" },
  { value: "ANISACATE", label: "ANISACATE" },
  { value: "ARIAS", label: "ARIAS" },
  { value: "ARROYITO", label: "ARROYITO" },
  { value: "ARROYO ALGODON", label: "ARROYO ALGODON" },
  { value: "ARROYO CABRAL", label: "ARROYO CABRAL" },
  { value: "ARROYO LOS PATOS", label: "ARROYO LOS PATOS" },
  { value: "ASSUNTA", label: "ASSUNTA" },
  { value: "ATAHONA", label: "ATAHONA" },
  { value: "AUSONIA", label: "AUSONIA" },
  { value: "AVELLANEDA", label: "AVELLANEDA" },
  { value: "BALLESTEROS SUD", label: "BALLESTEROS SUD" },
  { value: "BALLESTEROS", label: "BALLESTEROS" },
  { value: "BALNEARIA", label: "BALNEARIA" },
  { value: "BAÑADO DE SOTO", label: "BAÑADO DE SOTO" },
  { value: "BELL VILLE", label: "BELL VILLE" },
  { value: "BENGOLEA", label: "BENGOLEA" },
  { value: "BENJAMIN GOULD", label: "BENJAMIN GOULD" },
  { value: "BERROTARAN", label: "BERROTARAN" },
  { value: "BIALET MASSE", label: "BIALET MASSE" },
  { value: "BOUWER", label: "BOUWER" },
  { value: "BRINKMANN", label: "BRINKMANN" },
  { value: "BUCHARDO", label: "BUCHARDO" },
  { value: "BULNES", label: "BULNES" },
  { value: "CABALANGO", label: "CABALANGO" },
  { value: "CALCHIN OESTE", label: "CALCHIN OESTE" },
  { value: "CALCHIN", label: "CALCHIN" },
  { value: "CALMAYO", label: "CALMAYO" },
  { value: "CAMILO ALDAO", label: "CAMILO ALDAO" },
  { value: "CAMINIAGA", label: "CAMINIAGA" },
  { value: "CAÑADA DE LUQUE", label: "CAÑADA DE LUQUE" },
  { value: "CAÑADA DE MACHADO", label: "CAÑADA DE MACHADO" },
  { value: "CAÑADA DE RIO PINTO", label: "CAÑADA DE RIO PINTO" },
  { value: "CAÑADA DEL SAUCE", label: "CAÑADA DEL SAUCE" },
  { value: "CANALS", label: "CANALS" },
  { value: "CANDELARIA SUD", label: "CANDELARIA SUD" },
  { value: "CAPILLA DE LOS REMEDIOS", label: "CAPILLA DE LOS REMEDIOS" },
  { value: "CAPILLA DEL CARMEN", label: "CAPILLA DEL CARMEN" },
  { value: "CAPILLA DEL MONTE", label: "CAPILLA DEL MONTE" },
  { value: "CAPILLA DEL SITON", label: "CAPILLA DEL SITON" },
  {
    value: "CAPITAN GENERAL BERNARDO O HIGGINS",
    label: "CAPITAN GENERAL BERNARDO O HIGGINS",
  },
  { value: "CARNERILLO", label: "CARNERILLO" },
  { value: "CARRILOBO", label: "CARRILOBO" },
  { value: "CASA GRANDE", label: "CASA GRANDE" },
  { value: "CAVANAGH", label: "CAVANAGH" },
  { value: "CERRO COLORADO", label: "CERRO COLORADO" },
  { value: "CHAJAN", label: "CHAJAN" },
  { value: "CHALACEA", label: "CHALACEA" },
  { value: "CHAÑAR VIEJO", label: "CHAÑAR VIEJO" },
  { value: "CHANCANI", label: "CHANCANI" },
  { value: "CHARBONIER", label: "CHARBONIER" },
  { value: "CHARRAS", label: "CHARRAS" },
  { value: "CHAZON", label: "CHAZON" },
  { value: "CHILIBROSTE", label: "CHILIBROSTE" },
  { value: "CHUCUL", label: "CHUCUL" },
  { value: "CHUÑA HUASI", label: "CHUÑA HUASI" },
  { value: "CHUÑA", label: "CHUÑA" },
  { value: "CHURQUI CAÑADA", label: "CHURQUI CAÑADA" },
  { value: "CIENAGA DEL CORO", label: "CIENAGA DEL CORO" },
  { value: "CINTRA", label: "CINTRA" },
  { value: "COLAZO", label: "COLAZO" },
  { value: "COLONIA ALMADA", label: "COLONIA ALMADA" },
  { value: "COLONIA ANITA", label: "COLONIA ANITA" },
  { value: "COLONIA BARGE", label: "COLONIA BARGE" },
  { value: "COLONIA BISMARCK", label: "COLONIA BISMARCK" },
  { value: "COLONIA BREMEN", label: "COLONIA BREMEN" },
  { value: "COLONIA CAROYA", label: "COLONIA CAROYA" },
  { value: "COLONIA ITALIANA", label: "COLONIA ITALIANA" },
  { value: "COLONIA ITURRASPE", label: "COLONIA ITURRASPE" },
  {
    value: "COLONIA LAS CUATRO ESQUINAS",
    label: "COLONIA LAS CUATRO ESQUINAS",
  },
  { value: "COLONIA LAS PICHANAS", label: "COLONIA LAS PICHANAS" },
  { value: "COLONIA MARINA", label: "COLONIA MARINA" },
  { value: "COLONIA PROSPERIDAD", label: "COLONIA PROSPERIDAD" },
  { value: "COLONIA SAN BARTOLOME", label: "COLONIA SAN BARTOLOME" },
  { value: "COLONIA SAN PEDRO", label: "COLONIA SAN PEDRO" },
  { value: "COLONIA TIROLESA", label: "COLONIA TIROLESA" },
  { value: "COLONIA VALTELINA", label: "COLONIA VALTELINA" },
  { value: "COLONIA VICENTE AGÃœERO", label: "COLONIA VICENTE AGÃœERO" },
  { value: "COLONIA VIDELA", label: "COLONIA VIDELA" },
  { value: "COLONIA VIGNAUD", label: "COLONIA VIGNAUD" },
  { value: "COMECHINGONES", label: "COMECHINGONES" },
  { value: "CONLARA", label: "CONLARA" },
  { value: "COPACABANA", label: "COPACABANA" },
  { value: "CORDOBA", label: "CORDOBA" },
  { value: "CORONEL BAIGORRIA", label: "CORONEL BAIGORRIA" },
  { value: "CORONEL MOLDES", label: "CORONEL MOLDES" },
  { value: "CORRAL DE BUSTOS", label: "CORRAL DE BUSTOS" },
  { value: "CORRALITO", label: "CORRALITO" },
  { value: "COSQUIN", label: "COSQUIN" },
  { value: "COSTASACATE", label: "COSTASACATE" },
  { value: "CRUZ ALTA", label: "CRUZ ALTA" },
  { value: "CRUZ DE CAÑA", label: "CRUZ DE CAÑA" },
  { value: "CRUZ DEL EJE", label: "CRUZ DEL EJE" },
  { value: "CUESTA BLANCA", label: "CUESTA BLANCA" },
  { value: "DALMACIO VELEZ", label: "DALMACIO VELEZ" },
  { value: "DEAN FUNES", label: "DEAN FUNES" },
  { value: "DEL CAMPILLO", label: "DEL CAMPILLO" },
  { value: "DESPEÑADEROS", label: "DESPEÑADEROS" },
  { value: "DEVOTO", label: "DEVOTO" },
  { value: "DIEGO DE ROJAS", label: "DIEGO DE ROJAS" },
  { value: "DIQUE CHICO", label: "DIQUE CHICO" },
  { value: "EL ARAÑADO", label: "EL ARAÑADO" },
  { value: "EL BRETE", label: "EL BRETE" },
  { value: "EL CHACHO", label: "EL CHACHO" },
  { value: "EL CRISPIN", label: "EL CRISPIN" },
  { value: "EL FORTIN", label: "EL FORTIN" },
  { value: "EL MANZANO", label: "EL MANZANO" },
  { value: "EL RASTREADOR", label: "EL RASTREADOR" },
  { value: "EL RODEO", label: "EL RODEO" },
  { value: "EL TIO", label: "EL TIO" },
  { value: "ELENA", label: "ELENA" },
  { value: "EMBALSE", label: "EMBALSE" },
  { value: "ESQUINA", label: "ESQUINA" },
  { value: "ESTACION GENERAL PAZ", label: "ESTACION GENERAL PAZ" },
  { value: "ESTACION JUAREZ CELMAN", label: "ESTACION JUAREZ CELMAN" },
  { value: "ESTANCIA DE GUADALUPE", label: "ESTANCIA DE GUADALUPE" },
  { value: "ESTANCIA VIEJA", label: "ESTANCIA VIEJA" },
  { value: "ETRURIA", label: "ETRURIA" },
  { value: "EUFRACIO LOZA", label: "EUFRACIO LOZA" },
  { value: "FALDA DEL CARMEN", label: "FALDA DEL CARMEN" },
  { value: "FREYRE", label: "FREYRE" },
  { value: "GENERAL BALDISSERA", label: "GENERAL BALDISSERA" },
  { value: "GENERAL CABRERA", label: "GENERAL CABRERA" },
  { value: "GENERAL DEHEZA", label: "GENERAL DEHEZA" },
  { value: "GENERAL FOTHERINGHAM", label: "GENERAL FOTHERINGHAM" },
  { value: "GENERAL LEVALLE", label: "GENERAL LEVALLE" },
  { value: "GENERAL ROCA", label: "GENERAL ROCA" },
  { value: "GUANACO MUERTO", label: "GUANACO MUERTO" },
  { value: "GUASAPAMPA", label: "GUASAPAMPA" },
  { value: "GUATIMOZIN", label: "GUATIMOZIN" },
  { value: "GUTEMBERG", label: "GUTEMBERG" },
  { value: "HERNANDO", label: "HERNANDO" },
  { value: "HUANCHILLA", label: "HUANCHILLA" },
  { value: "HUERTA GRANDE", label: "HUERTA GRANDE" },
  { value: "HUINCA RENANCO", label: "HUINCA RENANCO" },
  { value: "IDIAZABAL", label: "IDIAZABAL" },
  { value: "IMPIRA", label: "IMPIRA" },
  { value: "INRIVILLE", label: "INRIVILLE" },
  { value: "ISLA VERDE", label: "ISLA VERDE" },
  { value: "ITALO", label: "ITALO" },
  { value: "JAMES CRAIK", label: "JAMES CRAIK" },
  { value: "JESUS MARIA", label: "JESUS MARIA" },
  { value: "JOVITA", label: "JOVITA" },
  { value: "JUSTINIANO POSSE", label: "JUSTINIANO POSSE" },
  { value: "KILOMETRO 658", label: "KILOMETRO 658" },
  { value: "LA BATEA", label: "LA BATEA" },
  { value: "LA CALERA", label: "LA CALERA" },
  { value: "LA CARLOTA", label: "LA CARLOTA" },
  { value: "LA CAROLINA EL POTOSI", label: "LA CAROLINA EL POTOSI" },
  { value: "LA CAUTIVA", label: "LA CAUTIVA" },
  { value: "LA CESIRA", label: "LA CESIRA" },
  { value: "LA CRUZ", label: "LA CRUZ" },
  { value: "LA CUMBRE", label: "LA CUMBRE" },
  { value: "LA CUMBRECITA", label: "LA CUMBRECITA" },
  { value: "LA FALDA", label: "LA FALDA" },
  { value: "LA FRANCIA", label: "LA FRANCIA" },
  { value: "LA GRANJA", label: "LA GRANJA" },
  { value: "LA HIGUERA", label: "LA HIGUERA" },
  { value: "LA LAGUNA", label: "LA LAGUNA" },
  { value: "LA PAISANITA", label: "LA PAISANITA" },
  { value: "LA PALESTINA", label: "LA PALESTINA" },
  { value: "LA PAMPA", label: "LA PAMPA" },
  { value: "LA PAQUITA", label: "LA PAQUITA" },
  { value: "LA PARA", label: "LA PARA" },
  { value: "LA PAZ", label: "LA PAZ" },
  { value: "LA PLAYA", label: "LA PLAYA" },
  { value: "LA PLAYOSA", label: "LA PLAYOSA" },
  { value: "LA POBLACION", label: "LA POBLACION" },
  { value: "LA POSTA", label: "LA POSTA" },
  { value: "LA PUERTA", label: "LA PUERTA" },
  { value: "LA QUINTA", label: "LA QUINTA" },
  { value: "LA RANCHERITA", label: "LA RANCHERITA" },
  { value: "LA RINCONADA", label: "LA RINCONADA" },
  { value: "LA SERRANITA", label: "LA SERRANITA" },
  { value: "LA TORDILLA", label: "LA TORDILLA" },
  { value: "LABORDE", label: "LABORDE" },
  { value: "LABOULAYE", label: "LABOULAYE" },
  { value: "LAGUNA LARGA", label: "LAGUNA LARGA" },
  { value: "LAS ACEQUIAS", label: "LAS ACEQUIAS" },
  { value: "LAS ALBAHACAS", label: "LAS ALBAHACAS" },
  { value: "LAS ARRIAS", label: "LAS ARRIAS" },
  { value: "LAS BAJADAS", label: "LAS BAJADAS" },
  { value: "LAS CALERAS", label: "LAS CALERAS" },
  { value: "LAS CALLES", label: "LAS CALLES" },
  { value: "LAS CAÑADAS", label: "LAS CAÑADAS" },
  { value: "LAS GRAMILLAS", label: "LAS GRAMILLAS" },
  { value: "LAS HIGUERAS", label: "LAS HIGUERAS" },
  { value: "LAS ISLETILLAS", label: "LAS ISLETILLAS" },
  { value: "LAS JUNTURAS", label: "LAS JUNTURAS" },
  { value: "LAS PALMAS", label: "LAS PALMAS" },
  { value: "LAS PEÑAS SUD", label: "LAS PEÑAS SUD" },
  { value: "LAS PEÑAS", label: "LAS PEÑAS" },
  { value: "LAS PERDICES", label: "LAS PERDICES" },
  { value: "LAS PLAYAS", label: "LAS PLAYAS" },
  { value: "LAS RABONAS", label: "LAS RABONAS" },
  { value: "LAS SALADAS", label: "LAS SALADAS" },
  { value: "LAS TAPIAS", label: "LAS TAPIAS" },
  { value: "LAS VARAS", label: "LAS VARAS" },
  { value: "LAS VARILLAS", label: "LAS VARILLAS" },
  { value: "LAS VERTIENTES", label: "LAS VERTIENTES" },
  { value: "LEGUIZAMON", label: "LEGUIZAMON" },
  { value: "LEONES", label: "LEONES" },
  { value: "LOS CEDROS", label: "LOS CEDROS" },
  { value: "LOS CERRILLOS", label: "LOS CERRILLOS" },
  { value: "LOS CHAÑARITOS (C. D. E.)", label: "LOS CHAÑARITOS (C. D. E.)" },
  { value: "LOS CHAÑARITOS", label: "LOS CHAÑARITOS" },
  { value: "LOS CISNES", label: "LOS CISNES" },
  { value: "LOS COCOS", label: "LOS COCOS" },
  { value: "LOS CONDORES", label: "LOS CONDORES" },
  { value: "LOS HORNILLOS", label: "LOS HORNILLOS" },
  { value: "LOS HOYOS", label: "LOS HOYOS" },
  { value: "LOS MISTOLES", label: "LOS MISTOLES" },
  { value: "LOS MOLINOS", label: "LOS MOLINOS" },
  { value: "LOS POZOS", label: "LOS POZOS" },
  { value: "LOS REARTES", label: "LOS REARTES" },
  { value: "LOS SURGENTES", label: "LOS SURGENTES" },
  { value: "LOS TALARES", label: "LOS TALARES" },
  { value: "LOS ZORROS", label: "LOS ZORROS" },
  { value: "LOZADA", label: "LOZADA" },
  { value: "LUCA", label: "LUCA" },
  { value: "LUCIO VICTORIO MANSILLA", label: "LUCIO VICTORIO MANSILLA" },
  { value: "LUQUE", label: "LUQUE" },
  { value: "LUTTI", label: "LUTTI" },
  { value: "LUYABA", label: "LUYABA" },
  { value: "MALAGUEÑO", label: "MALAGUEÑO" },
  { value: "MALENA", label: "MALENA" },
  { value: "MALVINAS ARGENTINAS", label: "MALVINAS ARGENTINAS" },
  { value: "MANFREDI", label: "MANFREDI" },
  { value: "MAQUINISTA GALLINI", label: "MAQUINISTA GALLINI" },
  { value: "MARCOS JUAREZ", label: "MARCOS JUAREZ" },
  { value: "MARULL", label: "MARULL" },
  { value: "MATORRALES", label: "MATORRALES" },
  { value: "MATTALDI", label: "MATTALDI" },
  { value: "MAYU SUMAJ", label: "MAYU SUMAJ" },
  { value: "MEDIA NARANJA", label: "MEDIA NARANJA" },
  { value: "MELO", label: "MELO" },
  { value: "MENDIOLAZA", label: "MENDIOLAZA" },
  { value: "MI GRANJA", label: "MI GRANJA" },
  { value: "MINA CLAVERO", label: "MINA CLAVERO" },
  { value: "MIRAMAR", label: "MIRAMAR" },
  { value: "MONTE BUEY", label: "MONTE BUEY" },
  { value: "MONTE CRISTO", label: "MONTE CRISTO" },
  { value: "MONTE DE LOS GAUCHOS", label: "MONTE DE LOS GAUCHOS" },
  { value: "MONTE LEÑA", label: "MONTE LEÑA" },
  { value: "MONTE MAIZ", label: "MONTE MAIZ" },
  { value: "MONTE RALO", label: "MONTE RALO" },
  { value: "MORRISON", label: "MORRISON" },
  { value: "MORTEROS", label: "MORTEROS" },
  { value: "NICOLAS BRUZZONE", label: "NICOLAS BRUZZONE" },
  { value: "NOETINGER", label: "NOETINGER" },
  { value: "NONO", label: "NONO" },
  { value: "OBISPO TREJO", label: "OBISPO TREJO" },
  { value: "OLAETA", label: "OLAETA" },
  { value: "OLIVA", label: "OLIVA" },
  { value: "OLIVARES DE SAN NICOLAS", label: "OLIVARES DE SAN NICOLAS" },
  { value: "ONAGOITY", label: "ONAGOITY" },
  { value: "ONCATIVO", label: "ONCATIVO" },
  { value: "ORDOÑEZ", label: "ORDOÑEZ" },
  { value: "PACHECO DE MELO", label: "PACHECO DE MELO" },
  { value: "PAMPAYASTA NORTE", label: "PAMPAYASTA NORTE" },
  { value: "PAMPAYASTA SUD", label: "PAMPAYASTA SUD" },
  { value: "PANAHOLMA", label: "PANAHOLMA" },
  { value: "PASCANAS", label: "PASCANAS" },
  { value: "PASCO", label: "PASCO" },
  { value: "PASO DEL DURAZNO", label: "PASO DEL DURAZNO" },
  { value: "PASO VIEJO", label: "PASO VIEJO" },
  { value: "PILAR", label: "PILAR" },
  { value: "PINCEN", label: "PINCEN" },
  { value: "PIQUILLIN", label: "PIQUILLIN" },
  { value: "PLAZA DE MERCEDES", label: "PLAZA DE MERCEDES" },
  { value: "PLAZA LUXARDO", label: "PLAZA LUXARDO" },
  { value: "PORTEÑA", label: "PORTEÑA" },
  { value: "POTRERO DE GARAY", label: "POTRERO DE GARAY" },
  { value: "POZO DEL MOLLE", label: "POZO DEL MOLLE" },
  { value: "POZO NUEVO", label: "POZO NUEVO" },
  { value: "PUEBLO ITALIANO", label: "PUEBLO ITALIANO" },
  { value: "PUESTO DE CASTRO", label: "PUESTO DE CASTRO" },
  { value: "PUNTA DEL AGUA", label: "PUNTA DEL AGUA" },
  { value: "QUEBRACHO HERRADO", label: "QUEBRACHO HERRADO" },
  { value: "QUILINO", label: "QUILINO" },
  { value: "RAFAEL GARCIA", label: "RAFAEL GARCIA" },
  { value: "RANQUELES", label: "RANQUELES" },
  { value: "RAYO CORTADO", label: "RAYO CORTADO" },
  { value: "REDUCCION", label: "REDUCCION" },
  { value: "RINCON", label: "RINCON" },
  { value: "RIO CEBALLOS", label: "RIO CEBALLOS" },
  { value: "RIO CUARTO", label: "RIO CUARTO" },
  { value: "RIO DE LOS SAUCES", label: "RIO DE LOS SAUCES" },
  { value: "RIO PRIMERO", label: "RIO PRIMERO" },
  { value: "RIO SEGUNDO", label: "RIO SEGUNDO" },
  { value: "RIO TERCERO", label: "RIO TERCERO" },
  { value: "RIOBAMBA", label: "RIOBAMBA" },
  { value: "ROSALES", label: "ROSALES" },
  { value: "ROSARIO DEL SALADILLO", label: "ROSARIO DEL SALADILLO" },
  { value: "SACANTA", label: "SACANTA" },
  { value: "SAGRADA FAMILIA", label: "SAGRADA FAMILIA" },
  { value: "SAIRA", label: "SAIRA" },
  { value: "SALADILLO", label: "SALADILLO" },
  { value: "SALDAN", label: "SALDAN" },
  { value: "SALSACATE", label: "SALSACATE" },
  { value: "SALSIPUEDES", label: "SALSIPUEDES" },
  { value: "SAMPACHO", label: "SAMPACHO" },
  { value: "SAN AGUSTIN", label: "SAN AGUSTIN" },
  { value: "SAN ANTONIO DE ARREDONDO", label: "SAN ANTONIO DE ARREDONDO" },
  { value: "SAN ANTONIO DE LITIN", label: "SAN ANTONIO DE LITIN" },
  { value: "SAN BASILIO", label: "SAN BASILIO" },
  { value: "SAN CARLOS MINAS", label: "SAN CARLOS MINAS" },
  { value: "SAN CLEMENTE", label: "SAN CLEMENTE" },
  { value: "SAN ESTEBAN", label: "SAN ESTEBAN" },
  { value: "SAN FRANCISCO DEL CHAÑAR", label: "SAN FRANCISCO DEL CHAÑAR" },
  { value: "SAN FRANCISCO", label: "SAN FRANCISCO" },
  { value: "SAN GERONIMO", label: "SAN GERONIMO" },
  { value: "SAN IGNACIO", label: "SAN IGNACIO" },
  { value: "SAN JAVIER Y YACANTO", label: "SAN JAVIER Y YACANTO" },
  { value: "SAN JOAQUIN", label: "SAN JOAQUIN" },
  { value: "SAN JOSE DE LA DORMIDA", label: "SAN JOSE DE LA DORMIDA" },
  { value: "SAN JOSE DE LAS SALINAS", label: "SAN JOSE DE LAS SALINAS" },
  { value: "SAN JOSE", label: "SAN JOSE" },
  { value: "SAN LORENZO", label: "SAN LORENZO" },
  { value: "SAN MARCOS SIERRAS", label: "SAN MARCOS SIERRAS" },
  { value: "SAN MARCOS SUD", label: "SAN MARCOS SUD" },
  { value: "SAN PEDRO NORTE", label: "SAN PEDRO NORTE" },
  { value: "SAN PEDRO", label: "SAN PEDRO" },
  { value: "SAN ROQUE", label: "SAN ROQUE" },
  { value: "SAN VICENTE", label: "SAN VICENTE" },
  { value: "SANTA CATALINA", label: "SANTA CATALINA" },
  { value: "SANTA ELENA", label: "SANTA ELENA" },
  { value: "SANTA EUFEMIA", label: "SANTA EUFEMIA" },
  { value: "SANTA MARIA DE PUNILLA", label: "SANTA MARIA DE PUNILLA" },
  { value: "SANTA ROSA DE CALAMUCHITA", label: "SANTA ROSA DE CALAMUCHITA" },
  { value: "SANTA ROSA DE RIO PRIMERO", label: "SANTA ROSA DE RIO PRIMERO" },
  { value: "SANTIAGO TEMPLE", label: "SANTIAGO TEMPLE" },
  { value: "SARMIENTO", label: "SARMIENTO" },
  { value: "SATURNINO MARIA LASPIUR", label: "SATURNINO MARIA LASPIUR" },
  { value: "SAUCE ARRIBA", label: "SAUCE ARRIBA" },
  { value: "SEBASTIAN ELCANO", label: "SEBASTIAN ELCANO" },
  { value: "SEEBER", label: "SEEBER" },
  { value: "SEGUNDA USINA", label: "SEGUNDA USINA" },
  { value: "SERRANO", label: "SERRANO" },
  { value: "SERREZUELA", label: "SERREZUELA" },
  { value: "SILVIO PELLICO", label: "SILVIO PELLICO" },
  { value: "SIMBOLAR", label: "SIMBOLAR" },
  { value: "SINSACATE", label: "SINSACATE" },
  { value: "SUCO", label: "SUCO" },
  { value: "TALA CAÑADA", label: "TALA CAÑADA" },
  { value: "TALA HUASI", label: "TALA HUASI" },
  { value: "TALAINI", label: "TALAINI" },
  { value: "TANCACHA", label: "TANCACHA" },
  { value: "TANTI", label: "TANTI" },
  { value: "TICINO", label: "TICINO" },
  { value: "TINOCO", label: "TINOCO" },
  { value: "TIO PUJIO", label: "TIO PUJIO" },
  { value: "TOLEDO", label: "TOLEDO" },
  { value: "TORO PUJIO", label: "TORO PUJIO" },
  { value: "TOSNO", label: "TOSNO" },
  { value: "TOSQUITA", label: "TOSQUITA" },
  { value: "TRANSITO", label: "TRANSITO" },
  { value: "TUCLAME", label: "TUCLAME" },
  { value: "UCACHA", label: "UCACHA" },
  { value: "UNQUILLO", label: "UNQUILLO" },
  { value: "VALLE DE ANISACATE", label: "VALLE DE ANISACATE" },
  { value: "VALLE HERMOSO", label: "VALLE HERMOSO" },
  { value: "VIAMONTE", label: "VIAMONTE" },
  { value: "VICUÑA MACKENNA", label: "VICUÑA MACKENNA" },
  { value: "VILLA ALLENDE", label: "VILLA ALLENDE" },
  { value: "VILLA AMANCAY", label: "VILLA AMANCAY" },
  { value: "VILLA ASCASUBI", label: "VILLA ASCASUBI" },
  { value: "VILLA CANDELARIA NORTE", label: "VILLA CANDELARIA NORTE" },
  { value: "VILLA CARLOS PAZ", label: "VILLA CARLOS PAZ" },
  { value: "VILLA CERRO AZUL", label: "VILLA CERRO AZUL" },
  { value: "VILLA CIUDAD DE AMERICA", label: "VILLA CIUDAD DE AMERICA" },
  {
    value: "VILLA CIUDAD PARQUE LOS REARTES",
    label: "VILLA CIUDAD PARQUE LOS REARTES",
  },
  { value: "VILLA CONCEPCION DEL TIO", label: "VILLA CONCEPCION DEL TIO" },
  { value: "VILLA CURA BROCHERO", label: "VILLA CURA BROCHERO" },
  { value: "VILLA DE LAS ROSAS", label: "VILLA DE LAS ROSAS" },
  { value: "VILLA DE MARIA", label: "VILLA DE MARIA" },
  { value: "VILLA DE POCHO", label: "VILLA DE POCHO" },
  { value: "VILLA DE SOTO", label: "VILLA DE SOTO" },
  { value: "VILLA DEL DIQUE", label: "VILLA DEL DIQUE" },
  { value: "VILLA DEL PRADO", label: "VILLA DEL PRADO" },
  { value: "VILLA DEL ROSARIO", label: "VILLA DEL ROSARIO" },
  { value: "VILLA DEL TOTORAL", label: "VILLA DEL TOTORAL" },
  { value: "VILLA DOLORES", label: "VILLA DOLORES" },
  { value: "VILLA EL CHACAY", label: "VILLA EL CHACAY" },
  { value: "VILLA ELISA", label: "VILLA ELISA" },
  { value: "VILLA FONTANA", label: "VILLA FONTANA" },
  { value: "VILLA GENERAL BELGRANO", label: "VILLA GENERAL BELGRANO" },
  { value: "VILLA GIARDINO", label: "VILLA GIARDINO" },
  { value: "VILLA GUTIERREZ", label: "VILLA GUTIERREZ" },
  { value: "VILLA HUIDOBRO", label: "VILLA HUIDOBRO" },
  { value: "VILLA LA BOLSA", label: "VILLA LA BOLSA" },
  { value: "VILLA LOS AROMOS", label: "VILLA LOS AROMOS" },
  { value: "VILLA LOS PATOS", label: "VILLA LOS PATOS" },
  { value: "VILLA MARIA", label: "VILLA MARIA" },
  { value: "VILLA NUEVA", label: "VILLA NUEVA" },
  { value: "VILLA PARQUE SANTA ANA", label: "VILLA PARQUE SANTA ANA" },
  { value: "VILLA PARQUE SIQUIMAN", label: "VILLA PARQUE SIQUIMAN" },
  { value: "VILLA QUILLINZO", label: "VILLA QUILLINZO" },
  { value: "VILLA RIO ICHO CRUZ", label: "VILLA RIO ICHO CRUZ" },
  { value: "VILLA ROSSI", label: "VILLA ROSSI" },
  { value: "VILLA RUMIPAL", label: "VILLA RUMIPAL" },
  { value: "VILLA SAN ESTEBAN", label: "VILLA SAN ESTEBAN" },
  { value: "VILLA SAN ISIDRO", label: "VILLA SAN ISIDRO" },
  { value: "VILLA SANTA CRUZ DEL LAGO", label: "VILLA SANTA CRUZ DEL LAGO" },
  { value: "VILLA SARMIENTO (G. R.)", label: "VILLA SARMIENTO (G. R.)" },
  { value: "VILLA SARMIENTO (S. A.)", label: "VILLA SARMIENTO (S. A.)" },
  { value: "VILLA TULUMBA", label: "VILLA TULUMBA" },
  { value: "VILLA VALERIA", label: "VILLA VALERIA" },
  { value: "VILLA YACANTO", label: "VILLA YACANTO" },
  { value: "WASHINGTON", label: "WASHINGTON" },
  { value: "WENCESLAO ESCALANTE", label: "WENCESLAO ESCALANTE" },
];
